# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile

tasks: 

- name: Update NPM 
  init: |
    npm update -g 
    gp-sync done npmu 
  command: npm --version

- name: Install http-server
  init: |
    gp-sync wait npmu
    npm install --global http-server
  openMode: split-right

- name: Run http server 
  init: gp-sync wait npmu
  command: http-server
  openMode: split-right

- name: Work Here 
  init: gp-sync wait npmu 
  command: echo "Work here dummy"
  openMode: split-right


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000-9000
    onOpen: open-preview
    visibility: public
