# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.dockerfile
  
tasks: 

- name: Plantuml Install 
  init: brew install plantuml 
  command: plantuml -version
  openMode: tab-after



# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000-9000
    onOpen: open-preview
    visibility: public
