# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile

tasks: 

  - name: Update NPM 
    init: |
      npm update -g
      gp sync-done unpm
    command: npm --version

  - name: Install http-server
    init: |
      gp sync-await unpm
      npm install --global http-server
    openMode: split-right

  - name: Http-server open port
    init: | 
      gp sync-await unpm
    command: http-server -p 8080

  - name: Work Here 
    init: | 
      gp sync-await unpm 
    command: echo "Work here dummy"
    openMode: tab-after


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000-9000
    onOpen: open-preview
    visibility: public
