@startuml 

/'
This proess is flow is being created for this - https://github.com/morektz/MorektzBountySmash/blob/main/D/qbrzg.md
Being created here for consolidation of diagrams.
'/

'Scale 

Scale 2 

'Styling 

skinparam {
    DefaultTextAlignment Center
    DefaultFontName DejaVu Sans 
    ArrowColor Black
    backgroundColor Black
    TitleFontColor E900FF
    Shadowing False

    HeaderFontColor FF008E
    HeaderFontName Monospace
    HeaderFontSize 12

    ActorBackgroundColor Black/Red
    ActorBorderColor 06FF00
}


center header 
---
%date()
Discord - morektz#7282
---
end header 

title 
=Zcash Foundation - Grants - Generic Process flow 

end title 

' Actor 

Actor as m1 



@enduml
