@startmindmap

/' 
This is based off this article 
https://solana.com/news/getting-started-with-solana-development
This generates the stuff mentioned in the above link
'/
 
' Scaling - size 
scale 2

' Styling

skinparam {
    DefaultTextAlignment Center
    DefaultFontName Roboto
    ArrowColor Black
    backgroundColor Black
    TitleFontColor E900FF
    Shadowing False
}

' Styling section 

<style>

'Root Note

' Node means all the boxes 
node {
    BackgroundColor 000D6B
    FontColor White
    LineColor Deeppink
}

rootNode {
    FontColor Magenta
}
arrow {
    LineColor Gold
}

</style>


header 
---
%date()
Discord - morektz#7282
---
end header 

title 
= Solana Programs Overview 

Native Programs = Solana contains a small handful of native programs, 
which are required to run validator nodes
SPL (Solana Program Library) = The Solana Program Library (SPL) is a collection of 
on-chain programs targeting the Sealevel parallel runtime

Src 
https://solana.com/news/getting-started-with-solana-development



end title 




+ Solana

++ Native \n Programs
+++ 1 System
++++ Create new accounts, \n allocate account data, \n assign accounts to \n owning programs, transfer lamports from \n System Program owned accounts and \n pay transaction fees.
+++ 2 Config
++++ Add configuration data \n to the chain and the list of \npublic keys that are permitted to modify it 
+++ 3 Stake 
++++ Create and manage accounts \n representing stake and rewards \n for delegations to validators.
+++ 4 Vote 
++++ Create and manage accounts \n that track validator voting state and rewards.
+++ 5 BPF \n Loader 
++++ Deploys, upgrades, and \n executes programs on the chain.
+++ 6 Ed25519 
++++ Verify ed25519 signature program. \n This program takes an \n ed25519 signature, public key, and message. \n Multiple signatures can be verified. \n If any of the signatures fail to verify, \n an error is returned.
+++ 7 Secp256k1
++++ Verify secp256k1 public key \n recovery operations (ecrecover). 

-- SPL (Solana \n Program \n Library)
--- 1 Token 
---- Common implementation for \nFungible and Non Fungible tokens.
--- 2 Token Swap 
---- A Uniswap-like exchange for the Token program \n on the Solana blockchain, \n implementing \n multiple automated market maker (AMM) curves.
--- 3 Token-Lending 
---- A lending protocol for the \n Token program \n on the Solana blockchain \n inspired by Aave and Compound.
--- 4 Asociated \n Token \n account
---- This program defines the convention \n and provides the mechanism \n for mapping the user's wallet address \n to the associated token accounts they hold.
--- 5 Memo 
---- Validates a string of UTF-8 \n encoded characters and \n verifies that any accounts \n provided are signers of the transaction.
--- 6 Name\nService
---- Issuing and managing \n ownership of domain names, \n Solana Pubkeys, URLs, \n Twitter handles, \n ipfs cid's etc
--- 7 Shared \n Memory 
---- Optimized program that writes \n instruction data \n into the provided account's data
--- 8 Stake\nPool
---- Pooling together SOL to be staked \n by an off-chain agent running \n a Delegation Bot which \n redistributes the stakes across \n the network and tries \n to maximize censorship \n resistance and rewards.
--- 9 Feature \n Program \n Proposal 
---- The Feature Proposal Program \n provides a workflow for activation \n of Solana network features \n through community vote \n based on validator stake weight.
@endmindmap
